# Generated by Django 2.2.6 on 2019-10-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.TextField(blank=True, null=True)),
                ('start_long', models.TextField(blank=True, null=True)),
                ('stop_lat', models.TextField(blank=True, null=True)),
                ('stop_long', models.TextField(blank=True, null=True)),
                ('activity_id', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.TimeField()),
                ('moving_time', models.TimeField()),
                ('sport', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_sport', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.TextField(blank=True, null=True)),
                ('cycles', models.TextField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('max_cadence', models.IntegerField(blank=True, null=True)),
                ('avg_speed', models.TextField(blank=True, null=True)),
                ('max_speed', models.TextField(blank=True, null=True)),
                ('ascent', models.TextField(blank=True, null=True)),
                ('descent', models.TextField(blank=True, null=True)),
                ('max_temperature', models.TextField(blank=True, null=True)),
                ('min_temperature', models.TextField(blank=True, null=True)),
                ('avg_temperature', models.TextField(blank=True, null=True)),
                ('training_effect', models.TextField(blank=True, null=True)),
                ('anaerobic_training_effect', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitiesExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('weather', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('people', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'activities_extra_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.TextField(blank=True, null=True)),
                ('start_long', models.TextField(blank=True, null=True)),
                ('stop_lat', models.TextField(blank=True, null=True)),
                ('stop_long', models.TextField(blank=True, null=True)),
                ('lap', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.TimeField()),
                ('moving_time', models.TimeField()),
                ('distance', models.TextField(blank=True, null=True)),
                ('cycles', models.TextField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('max_cadence', models.IntegerField(blank=True, null=True)),
                ('avg_speed', models.TextField(blank=True, null=True)),
                ('max_speed', models.TextField(blank=True, null=True)),
                ('ascent', models.TextField(blank=True, null=True)),
                ('descent', models.TextField(blank=True, null=True)),
                ('max_temperature', models.TextField(blank=True, null=True)),
                ('min_temperature', models.TextField(blank=True, null=True)),
                ('avg_temperature', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_laps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('position_lat', models.TextField(blank=True, null=True)),
                ('position_long', models.TextField(blank=True, null=True)),
                ('distance', models.TextField(blank=True, null=True)),
                ('cadence', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('alititude', models.TextField(blank=True, null=True)),
                ('speed', models.TextField(blank=True, null=True)),
                ('temperature', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('vo2_max', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycle_activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EllipticalActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('elliptical_distance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elliptical_activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaddleActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('avg_stroke_distance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paddle_activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StepsActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('avg_pace', models.TimeField()),
                ('avg_moving_pace', models.TimeField()),
                ('max_pace', models.TimeField()),
                ('avg_steps_per_min', models.IntegerField(blank=True, null=True)),
                ('max_steps_per_min', models.IntegerField(blank=True, null=True)),
                ('avg_step_length', models.TextField(blank=True, null=True)),
                ('avg_vertical_ratio', models.TextField(blank=True, null=True)),
                ('avg_vertical_oscillation', models.TextField(blank=True, null=True)),
                ('avg_gct_balance', models.TextField(blank=True, null=True)),
                ('avg_ground_contact_time', models.TimeField()),
                ('avg_stance_time_percent', models.TextField(blank=True, null=True)),
                ('vo2_max', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'steps_activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'version',
                'managed': False,
            },
        ),
    ]
